// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package cassandra.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import cassandra.helpers.Cassandra;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_ExecuteQuery extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String query;
	private IMendixObject resultObject;

	public JA_ExecuteQuery(IContext context, java.lang.String query, IMendixObject resultObject)
	{
		super(context);
		this.query = query;
		this.resultObject = resultObject;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Cassandra.executeQuery(query, resultObject, this.getContext());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "JA_ExecuteQuery";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
